# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf


# TAB between workspaces
bindd = SUPER, K, Next workspace, workspace, e+1
bindd = SUPER, J, Previous workspace, workspace, e-1

bindd = SUPER, S, Next workspace, workspace, e+1
bindd = SUPER, A, Previous workspace, workspace, e-1

# bindd = SUPER, U, Next workspace, workspace, e+2
# bindd = SUPER, D, Previous workspace, workspace, e-2

bindd = SUPER, L, Former workspace, workspace, previous

bindd = SUPER ALT, code:10, Switch to workspace 11, workspace, 11
bindd = SUPER ALT, code:11, Switch to workspace 12, workspace, 12
bindd = SUPER ALT, code:12, Switch to workspace 13, workspace, 13
bindd = SUPER ALT, code:13, Switch to workspace 14, workspace, 14
bindd = SUPER ALT, code:14, Switch to workspace 15, workspace, 15
bindd = SUPER ALT, code:15, Switch to workspace 16, workspace, 16
bindd = SUPER ALT, code:16, Switch to workspace 17, workspace, 17
bindd = SUPER ALT, code:17, Switch to workspace 18, workspace, 18
bindd = SUPER ALT, code:18, Switch to workspace 19, workspace, 19
bindd = SUPER ALT, code:19, Switch to workspace 20, workspace, 20


input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
}

# bindl = , switch:Lid Switch, exec, systemctl suspend
